name: RamadaArtist
favicon: null
layout_spectrum: 0.52633
typography_spectrum: 0.90112
title: Personal Website of Matthew J Ramada
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0e12'
    - '#f7f7f9'
    - '#3f3b37'
    - '#8d7177'
    - '#98a2dc'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
