name: RamadaArtist
favicon: null
layout_spectrum: 0.7068344159051776
typography_spectrum: 0.22062411182560027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7bdbb'
    - '#110f40'
    - '#928484'
    - '#2b6686'
    - '#2296e6'
  brandStrength: 0.8125
  lightness: 0.601104412227869
  saturation: 0.6875
  rhythmicContrast: 0.32107436400838196
purpose: []
