name: RamadaArtist
favicon: null
layout_spectrum: 0.52633
typography_spectrum: 0.90112
title: Personal Website of the artist Matthew J Ramada
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#283c55'
    - '#8c939d'
    - '#8cc037'
    - '#fdec9e'
    - '#3172a8'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
