name: RamadaArtist
favicon: null
layout_spectrum: 0.71223
typography_spectrum: 0.83141
title: Personal Website of the artist Matthew J Ramada
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c081f'
    - '#4b3a33'
    - '#c3c5c2'
    - '#737069'
    - '#c18644'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
